
using Corporate_Banking_Payment_Application.DTOs;
using Corporate_Banking_Payment_Application.Models;


namespace Corporate_Banking_Payment_Application.Services.IService
{
    public interface IReportService
    {
 
        /// Orchestrates the process of generating a report, uploading the file to Cloudinary, 
        /// and saving the report metadata to the database
        Task<ReportDto> GenerateAndSaveReport(GenerateReportRequestDto request, int currentUserId, UserRole currentUserRole);


        /// Retrieves a list of reports previously generated by the specified user
        //Task<IEnumerable<ReportDto>> GetReportsByUser(int userId);
        Task<PagedResult<ReportDto>> GetReportsByUser(int userId, string? searchTerm, string? sortColumn, SortOrder? sortOrder, int pageNumber, int pageSize);


        /// Retrieves a single report record by ID
        Task<ReportDto?> GetReportById(int reportId);
    }
}
