using Corporate_Banking_Payment_Application.Data;
using Corporate_Banking_Payment_Application.Models;
using Corporate_Banking_Payment_Application.Repository.IRepository;
using Microsoft.EntityFrameworkCore;

namespace Corporate_Banking_Payment_Application.Repository
{
    public class ReportRepository : IReportRepository
    {
        private readonly AppDbContext _context;

        public ReportRepository(AppDbContext context)
        {
            _context = context;
        }


        /// Adds a new Report record to the database after successful file upload to Cloudinary.
        public async Task<Report> AddReport(Report report)
        {
            _context.Reports.Add(report);
            await _context.SaveChangesAsync();
            return report;
        }

        /// Retrieves a single report record by its ID
        public async Task<Report?> GetReportById(int id)
        {
            return await _context.Reports
                .AsNoTracking()
                .FirstOrDefaultAsync(r => r.ReportId == id);
        }


        /// Retrieves a list of reports generated by a specific user
        public async Task<IEnumerable<Report>> GetReportsByUserId(int userId)
        {
            return await _context.Reports
                .AsNoTracking()
                .Where(r => r.GeneratedBy == userId)
                // Order by newest first, as is common for reporting lists
                .OrderByDescending(r => r.GeneratedDate)
                .ToListAsync();
        }
    }
}
