using Corporate_Banking_Payment_Application.Data;
using Corporate_Banking_Payment_Application.Models;
using Corporate_Banking_Payment_Application.Repository.IRepository;
using Microsoft.EntityFrameworkCore;

namespace Corporate_Banking_Payment_Application.Repository
{
    public class ReportRepository : IReportRepository
    {
        private readonly AppDbContext _context;

        public ReportRepository(AppDbContext context)
        {
            _context = context;
        }

        /// <summary>
        /// Adds a new Report record to the database after successful file upload to Cloudinary.
        /// </summary>
        /// <param name="report">The Report entity to add.</param>
        /// <returns>The created Report entity.</returns>
        public async Task<Report> AddReport(Report report)
        {
            _context.Reports.Add(report);
            await _context.SaveChangesAsync();
            return report;
        }

        /// <summary>
        /// Retrieves a single report record by its ID.
        /// </summary>
        /// <param name="id">The ID of the report.</param>
        /// <returns>The Report entity, or null if not found.</returns>
        public async Task<Report?> GetReportById(int id)
        {
            return await _context.Reports
                .AsNoTracking()
                .FirstOrDefaultAsync(r => r.ReportId == id);
        }

        /// <summary>
        /// Retrieves a list of reports generated by a specific user.
        /// Reports are ordered by the newest generated date first.
        /// </summary>
        /// <param name="userId">The ID of the user who generated the reports.</param>
        /// <returns>A collection of Report entities.</returns>
        public async Task<IEnumerable<Report>> GetReportsByUserId(int userId)
        {
            return await _context.Reports
                .AsNoTracking()
                .Where(r => r.GeneratedBy == userId)
                // Order by newest first, as is common for reporting lists
                .OrderByDescending(r => r.GeneratedDate)
                .ToListAsync();
        }
    }
}
