using Corporate_Banking_Payment_Application.Models;

namespace Corporate_Banking_Payment_Application.Repository.IRepository
{
    public interface IReportRepository
    {

        /// Adds a new Report record to the database after successful file upload to Cloudinary.
        Task<Report> AddReport(Report report);


        /// Retrieves a list of reports generated by a specific user
        //Task<IEnumerable<Report>> GetReportsByUserId(int userId);
        Task<PagedResult<Report>> GetReportsByUserId(int userId, string? searchTerm, string? sortColumn, SortOrder? sortOrder, int pageNumber, int pageSize);


        /// Retrieves a single report record by its ID
        Task<Report?> GetReportById(int id);
    }
}
