using Corporate_Banking_Payment_Application.Models;

namespace Corporate_Banking_Payment_Application.Repository.IRepository
{
    public interface IReportRepository
    {
        /// <summary>
        /// Adds a new Report record to the database after successful file upload to Cloudinary.
        /// </summary>
        /// <param name="report">The Report entity to add.</param>
        /// <returns>The created Report entity.</returns>
        Task<Report> AddReport(Report report);

        /// <summary>
        /// Retrieves a list of reports generated by a specific user.
        /// </summary>
        /// <param name="userId">The ID of the user who generated the reports.</param>
        /// <returns>A collection of Report entities.</returns>
        Task<IEnumerable<Report>> GetReportsByUserId(int userId);

        /// <summary>
        /// Retrieves a single report record by its ID.
        /// </summary>
        /// <param name="id">The ID of the report.</param>
        /// <returns>The Report entity, or null if not found.</returns>
        Task<Report?> GetReportById(int id);
    }
}
